name: CI - Ecom Analytics Platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint Python code
        run: |
          flake8 producer consumer spark jobs || true

      - name: Validate Docker Compose
        run: |
          docker compose config

      - name: Build containers
        run: |
          docker compose build

      - name: Start core services
        run: |
          docker compose up -d postgres zookeeper kafka minio spark-master spark-worker

      - name: Wait for services
        run: sleep 20

      - name: Smoke test Kafka
        run: |
          docker compose exec -T kafka \
            kafka-topics --bootstrap-server kafka:9092 --list

      - name: Smoke test Spark
        run: |
          docker compose exec -T spark-master \
            /opt/spark/bin/spark-submit --version

      - name: Tear down
        if: always()
        run: |
          docker compose down -v